
version: "3"
services:
  api:
    build: api
    ports:
      - "1880:1880"
    volumes:
      - "./api/data:/data"
    links:
      - db
  db:
    image: tutum/mysql:5.6
    environment:
      - ON_CREATE_DB=ttn_test_db
    env_file:
      - ./env/mysql.env
    volumes:
      - "ttn-test-db-data:/var/lib/mysql"
volumes:
  ttn-test-db-data:
